ml_app/urls.py
"""project_settings URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import about, index, predict_page,cuda_full

app_name = 'ml_app'
handler404 = views.handler404

urlpatterns = [
    path('index/', index, name='index'),
    path('about/', about, name='about'),
    path('predict/', predict_page, name='predict'),
    path('cuda_full/',cuda_full,name='cuda_full'),
    path('', views.home, name='home'),
    path('getstarted/', views.getstarted, name='getstarted')
]

project_settings/urls.py
"""project_settings URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ml_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="/static/bootstrap/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
    <link rel="stylesheet" href="/static/css/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Deepfake Detection</title>

    
</head>
<body>
    {%include 'nav-bar.html'%}
    {%block content%}
    {%endblock%}
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-3.4.1.min.js" ></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script> -->
        <script src="/static/js/popper.min.js"></script>
    <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-ui.min.js"></script>
    
        {%block js_cripts%}
    {%endblock%}
    {%include 'footer.html'%}
</body>

</html>

templates/footer.html
<!-- <footer class="footer">
    <div class="container">
      <center><span class="text-muted" >Copyright @ {%now 'Y'%}</span></center>
      <!-- <a href="{% url 'ml_app:home'%}">Home</a>
      <a href="{% url 'ml_app:about'%}">About</a>
      <a href="#">Github Link</a>
    </div>
  </footer> -->

    <!-- Footer -->
    {% comment %} <footer style="background-color: #212936; color: white; padding: 20px 0; text-align: center;">
      <p style="margin: 0;">&copy; 2025 Deepify. All Rights Reserved.</p>
      <p style="margin: 0;">Designed by <a href="#" style="color: #FF7D14; text-decoration: none;">Team 9</a></p>
    </footer> {% endcomment %}


    {% load static %}
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
    <!-- Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

 

    <footer id="footer" class="footer dark-background w-100 m-0 p-0">
      <div class="container-fluid px-0">
        <div class="text-center py-4">
          <h3 class="sitename mb-2">{{ site_name|default:"Deepify" }}</h3>
          <p class="mb-3">
            {{ site_description|default:"We provide fast, accurate, and reliable deepfake detection to help you verify the authenticity of videos." }}
          </p>
          <div class="social-links d-flex justify-content-center gap-3 mb-3">
            <a href="{{ twitter_url|default:'#' }}"><i class="bi bi-twitter-x"></i></a>
            <a href="{{ facebook_url|default:'#' }}"><i class="bi bi-facebook"></i></a>
            <a href="{{ instagram_url|default:'#' }}"><i class="bi bi-instagram"></i></a>
            <a href="{{ linkedin_url|default:'#' }}"><i class="bi bi-linkedin"></i></a>
          </div>
          <div class="copyright mb-2">
            <span>&copy; {{ current_year|default:2025 }}</span>
            <strong class="px-1 sitename">{{ site_name|default:"Deepify" }}</strong>
            <span>All Rights Reserved</span>
          </div>
        </div>
      </div>
    </footer>
    

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

templates/nav-bar.html
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
    <!-- <a class="navbar-brand" href="#">Navbar</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:home'%}">Home</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:about'%}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">GitHub</a>
            </li> 
        </ul>
    </div>
</nav> -->

  <!-- Header -->
  {% load static %}
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
    <!-- Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

{% comment %} <header style="background-color: #212936; color: white; padding-top: 20px; padding-bottom: 20px; position: fixed; top: 0; width: 100%; z-index: 1000;">
    <div style="display: flex; justify-content: space-between; align-items: center; max-width: 1200px; margin: 0 auto; padding: 0 20px;">
      <a href="index.html" style="color: white; text-decoration: none;">
        <h1 style="margin: 0; font-size: 24px;">Deepify</h1>
      </a>
      <nav>
        <ul style="list-style: none; display: flex; gap: 20px; margin-bottom: 0px; padding: 0;">
          <li><a href="{% url 'ml_app:home' %}" style="color: #FF7D14; text-decoration: none;">Home</a></li>
          <li><a href="{% url 'contact' %}" style="color: white; text-decoration: none;">Team</a></li>
        </ul>
      </nav>
    </div>
  </header> {% endcomment %}

  <header id="header" class="header d-flex align-items-center fixed-top" style="background-color: #2a2c39;">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-around">

      <a href="{% url 'ml_app:home' %}" class="logo d-flex align-items-center">
        <h1 class="sitename">Deepify.</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'ml_app:home' %}" style="color: white; text-decoration: none;">Home</a></li>
          <li><a href="{% url 'ml_app:home' %}#about" style="color: white; text-decoration: none;">About</a></li>
          <li><a href="{% url 'ml_app:home' %}#team" style="color: white; text-decoration: none;">Team</a></li>
          <a href="{% url 'ml_app:index' %}"><button type="submit" id="redirectButton" class="btn-primary">Get Started</button></a>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>


    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  
    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  